baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Chad Steed's Website"
googleAnalytics = "UA-39778348-1"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]
  [[menu.nav]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "projects"
    url = "/projects/"
    weight = 2
  [[menu.nav]]
    name = "publications"
    url = "/publications/"
    weight = 3
  [[menu.nav]]
    name = "artwork"
    url = "/art/"
    weight = 5
  [[menu.nav]]
    name = "writings"
    url = "/writings/"
    weight = 6
  [[menu.nav]]
    name = "bio"
    url = "/bio/"
    weight = 7
  [[menu.nav]]
    name = "vita"
    url = "https://github.com/csteed/vitae/raw/master/chadsteed_cv.pdf"
    weight = 8

[params]
  showActiveNav = true
